# Generated by Django 3.1.5 on 2021-01-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='project_name',
        ),
    ]
