# Generated by Django 3.1.5 on 2021-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210112_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='project_tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
