# Generated by Django 3.1.5 on 2021-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_about_text_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text_right',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
