# Generated by Django 3.1.5 on 2021-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210121_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
