# Generated by Django 3.1.5 on 2021-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_contact_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_line_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_line_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
